name = "test-wrangler"
compatibility_date = "2023-12-01"
workers_dev = false
main = "./index.ts"
compatibility_flags = [ "nodejs_compat"]
# route = { pattern = "v2.api.capgo.app", custom_domain = true }
